% prepare Keyboard input
Key0 = KbName('0)');
Key1 = KbName('1!');
Key2 = KbName('2@');
Key3 = KbName('3#');
Key4 = KbName('4$');
Key5 = KbName('5%');
Key6 = KbName('6^');
Key7 = KbName('7&');
Key8 = KbName('8*');
Key9 = KbName('9(');
Keya = KbName('a');
Keyb = KbName('b');
Keyc = KbName('c');
Keyd = KbName('d');
Keye = KbName('e');
Keyf = KbName('f');
Keyg = KbName('g');
Keyh = KbName('h');
Keyi = KbName('i');
Keyj = KbName('j');
Keyk = KbName('k');
Keyl = KbName('l');
Keym = KbName('m');
Keyn = KbName('n');
Keyo = KbName('o');
Keyp = KbName('p');
Keyq = KbName('q');
Keyr = KbName('r');
Keys = KbName('s');
Keyt = KbName('t');
Keyu = KbName('u');
Keyv = KbName('v');
Keyw = KbName('w');
Keyx = KbName('x');
Keyy = KbName('y');
Keyz = KbName('z');
Keyf11 = KbName('f11');
Keyf12 = KbName('f12');
rightKey = KbName('right');	% 
leftKey = KbName('left');	% 
upKey = KbName('up');
downKey = KbName('down');
shiftKey = KbName('left_shift');   % left shift
ctrlKey = KbName('left_control'); % left ctrl
altKey = KbName('alt');   % left alt
pageupKey = KbName('pageup');
pagedownKey = KbName('pagedown');
spaceKey = KbName('space');
escapeKey = KbName('esc');	% quit key
