# -*- coding: utf-8 -*-
"""
Created on Fri Mar 12 15:10:43 2021

@author: ZR
This part of code is used to operate Stim_Frame_Aling files.
"""

def Frame_ID_Extractor(stim_dic,stim_ID_Lists):
    '''
    This program will extract any combination of Stim ID in already aligned dics.

    Parameters
    ----------
    stim_dic : (Dic)
        Frame stim dictionary generated by function 'Stim_Frame_Align'.
    stim_ID_Lists : (list)
        List of stim IDs you want.
        
    Returns
    -------
    frame_lists : (list)
        Frame ID List of wanted stims.

    '''
    frame_lists = []
    for i in range(len(stim_ID_Lists)):
        frame_lists.extend(stim_dic[stim_ID_Lists[i]])
    
    return frame_lists